// Generates supabase/seed.sql from catalog.js + sample-deals.js.
// Usage: node scripts/build-seed.js
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.join(__dirname, '..');
const ctx = { window: {} };
vm.createContext(ctx);
for (const f of ['catalog.js', 'sample-deals.js']) {
  vm.runInContext(fs.readFileSync(path.join(root, f), 'utf8'), ctx, { filename: f });
}
const deals = ctx.window.RAW_DEALS;
if (!deals || !deals.length) throw new Error('No deals found in sample-deals.js');

const today = new Date();
today.setHours(0, 0, 0, 0);
const iso = off => {
  const d = new Date(today);
  d.setDate(d.getDate() + off);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
};
const q = s => (s == null ? 'null' : "'" + String(s).replace(/'/g, "''") + "'");
const txt = a => (a && a.length ? 'array[' + a.map(q).join(',') + ']::text[]' : "'{}'::text[]");
const num = a => (a && a.length ? 'array[' + a.join(',') + ']::smallint[]' : "'{}'::smallint[]");

const rows = deals.map(d => {
  const s = d.sched;
  const all = d.cities === 'all';
  const range = s.t === 'range';
  return '      (' + [
    q(d.m), q(d.c), all, txt(all ? [] : d.cities), txt(d.banks), txt(d.types || ['credit', 'debit']),
    d.nets ? txt(d.nets) : 'null', q(d.offer), d.pct || 0, q(d.max), q(d.min),
    q(s.t), num(s.days), num(s.dates),
    range ? q(iso(s.from)) : 'null', range ? q(iso(s.to)) : 'null', q(d.terms)
  ].join(', ') + ')';
});

const sql = `-- Kard — sample seed (${deals.length} placeholder deals). Generated by scripts/build-seed.js.
-- Runs only if the deals table is empty. These are NOT real bank offers.
do $$
begin
  if not exists (select 1 from public.deals) then
    insert into public.deals
      (merchant, category, all_cities, cities, banks, card_types, networks, offer, discount_pct,
       max_discount, min_spend, schedule_type, weekdays, month_dates, start_date, end_date, terms)
    values
${rows.join(',\n')};
  end if;
end $$;
`;
fs.writeFileSync(path.join(root, 'supabase', 'seed.sql'), sql);
console.log('Wrote supabase/seed.sql with', deals.length, 'deals');
